/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.generics;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class GenericListTest {
    private GenericList<Integer> list = new GenericList<>();
    
    @Test
    void genericListTest () {
        
        list.addItem(1);
        assertFalse(list.isEmpty());
        
        assertEquals(1, list.getItem(0));
        assertNotEquals(0, list.getItem(0));

        assertSame(1, list.getItem(0));
        assertNotSame(0, list.getItem(0));
        
        list.addItem(null);
        assertNull(list.getItem(1));
        assertNotNull(list.getItem(0));        

        list.removeItem(0);
        assertFalse(list.isEmpty());
        list.removeItem(0);
        assertTrue(list.isEmpty());
       
    }
}